language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: azCZSQo/9M7dR3A4G7YbiOnPhKFBhM35YffZyacWXauQSHb36JpWrbHjhJFzgt2rpbaANlJFIWTyWHXSTRMFJ+neJHOcBD4gBqrHocSj1Bt+fsbkni2pz00NOkTon3+HeKZTu3inAhpTSl7Ujd+pOb09C4mG333HEOaqEpVuvwp50vz45/NKYZitMrPg9RF/UqeTr5Nk9cnwiNKykCcBg68bEh2KeAJeY3ugADdZMY21LIg+H1GBAw0v+rP8eszXC29B9m/D5tK5L2duitj5IRSRy2mY/XxMnQjzxqwc0sIx23PW1NMhHIKFz7JGUwSKF7RR6KGpH6IvfXkRIkpggI8eh9IVy87aQjeD3YNbvGgELz4JS/yUFQCRE8V8QLsELzBUu+6T5JEwbM/Lx5100XNcrTBMBsOsdK14lJoRqsx1ueTNol4myIda8ysRVdYHSLrHF/IYPeCawlK7ecZGQLZ9N3YzXO49KyB9FkY+ivGr8bva9tCtKmMTx415jybP8Zp/51ZVwVJavVgu2MpujvoaDSyAWfe4SwxgEJjr99iS4WdAPy35z/38Cvy04I1hFz4o3RhuJkLuqJK4hMo3RuTEd6O30NXUqCYfAM/Yjx0oDna9UkW4CYjlik/TI8fCNnT0hGFZFbeycOUgKEjJZ96wQdT4pxogUF0KO4u3RPg=
  app: y
  on:
    repo: thinkful-ei25/joshua-noteful-v3
